OBJECTS = 20171609.o
SRC = 20171609.c

CC = gcc
CFLAGS = -g -Wall -W

TARGET = 20171609.out

$(TARGET) : $(OBJECTS)
	$(CC) -o $(TARGET) $(OBJECTS) $(CFLAGS)

clean:
	rm $(OBJECTS) $(TARGET)
